// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// alg_non_linear
arma::mat alg_non_linear(arma::mat coeffs_input, ListOf<IntegerVector> labels_input, ListOf<IntegerVector> labels_output, IntegerVector taylor_orders, int current_layer, arma::vec g, ListOf<IntegerVector> partitions_labels, List partitions);
RcppExport SEXP _nn2poly_alg_non_linear(SEXP coeffs_inputSEXP, SEXP labels_inputSEXP, SEXP labels_outputSEXP, SEXP taylor_ordersSEXP, SEXP current_layerSEXP, SEXP gSEXP, SEXP partitions_labelsSEXP, SEXP partitionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type coeffs_input(coeffs_inputSEXP);
    Rcpp::traits::input_parameter< ListOf<IntegerVector> >::type labels_input(labels_inputSEXP);
    Rcpp::traits::input_parameter< ListOf<IntegerVector> >::type labels_output(labels_outputSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type taylor_orders(taylor_ordersSEXP);
    Rcpp::traits::input_parameter< int >::type current_layer(current_layerSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type g(gSEXP);
    Rcpp::traits::input_parameter< ListOf<IntegerVector> >::type partitions_labels(partitions_labelsSEXP);
    Rcpp::traits::input_parameter< List >::type partitions(partitionsSEXP);
    rcpp_result_gen = Rcpp::wrap(alg_non_linear(coeffs_input, labels_input, labels_output, taylor_orders, current_layer, g, partitions_labels, partitions));
    return rcpp_result_gen;
END_RCPP
}
// combinations_with_repetition
IntegerMatrix combinations_with_repetition(int n, int k);
RcppExport SEXP _nn2poly_combinations_with_repetition(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(combinations_with_repetition(n, k));
    return rcpp_result_gen;
END_RCPP
}
// generate_partitions
List generate_partitions(int p, int q_max);
RcppExport SEXP _nn2poly_generate_partitions(SEXP pSEXP, SEXP q_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q_max(q_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_partitions(p, q_max));
    return rcpp_result_gen;
END_RCPP
}
// filter_partitions_by_max_part_order
List filter_partitions_by_max_part_order(List global_partitions_obj, int max_part_order_filter);
RcppExport SEXP _nn2poly_filter_partitions_by_max_part_order(SEXP global_partitions_objSEXP, SEXP max_part_order_filterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type global_partitions_obj(global_partitions_objSEXP);
    Rcpp::traits::input_parameter< int >::type max_part_order_filter(max_part_order_filterSEXP);
    rcpp_result_gen = Rcpp::wrap(filter_partitions_by_max_part_order(global_partitions_obj, max_part_order_filter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nn2poly_alg_non_linear", (DL_FUNC) &_nn2poly_alg_non_linear, 8},
    {"_nn2poly_combinations_with_repetition", (DL_FUNC) &_nn2poly_combinations_with_repetition, 2},
    {"_nn2poly_generate_partitions", (DL_FUNC) &_nn2poly_generate_partitions, 2},
    {"_nn2poly_filter_partitions_by_max_part_order", (DL_FUNC) &_nn2poly_filter_partitions_by_max_part_order, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_nn2poly(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
