# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alg_non_linear <- function(coeffs_input, labels_input, labels_output, taylor_orders, current_layer, g, partitions_labels, partitions) {
    .Call(`_nn2poly_alg_non_linear`, coeffs_input, labels_input, labels_output, taylor_orders, current_layer, g, partitions_labels, partitions)
}

combinations_with_repetition <- function(n, k) {
    .Call(`_nn2poly_combinations_with_repetition`, n, k)
}

generate_partitions <- function(p, q_max) {
    .Call(`_nn2poly_generate_partitions`, p, q_max)
}

filter_partitions_by_max_part_order <- function(global_partitions_obj, max_part_order_filter) {
    .Call(`_nn2poly_filter_partitions_by_max_part_order`, global_partitions_obj, max_part_order_filter)
}

